[package]
name = "qimem"
version = "0.1.0"
edition = "2021"

[lib]
name = "qimem"
crate-type = ["rlib"]

[[bin]]
name = "qimem"
path = "src/bin/qimem.rs"

[[bin]]
name = "qimem-api"
path = "src/bin/qimem-api.rs"

[[bin]]
name = "qauth"
path = "src/bin/qauth.rs"

[[bin]]
name = "qauth-api"
path = "src/bin/qauth-api.rs"

[features]
default = []
chacha = ["dep:chacha20poly1305"]
stateful = ["dep:sqlx"]

[dependencies]
aes-gcm = "0.10"
axum = { version = "0.7", features = ["json"] }
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
dotenvy = "0.15"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.39", features = ["macros", "rt-multi-thread", "net"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
zeroize = "1.8"
subtle = "2.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
chacha20poly1305 = { version = "0.10", optional = true }
sqlx = { version = "0.7", optional = true, features = ["runtime-tokio", "postgres", "uuid", "migrate", "tls-rustls"] }
totp-rs = { version = "5.6", default-features = false, features = ["gen_secret", "otpauth"] }
jsonwebtoken = "9.3"
argon2 = "0.5"

[dev-dependencies]
tokio = { version = "1.39", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5", features = ["util"] }
reqwest = { version = "0.12", features = ["blocking", "json", "rustls-tls"] }
